on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Create S3 Bucket with Website Configuration
        run: |
          aws s3api create-bucket \
            --bucket bw-hunterdle-cs293-project.com \
            --region us-east-1

          aws s3api put-public-access-block \
            --bucket bw-hunterdle-cs293-project.com \
            --public-access-block-configuration "BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

          aws s3api put-bucket-website \
            --bucket bw-hunterdle-cs293-project.com \
            --website-configuration '{
                "IndexDocument": {
                    "Suffix": "index.html"
                },
                "ErrorDocument": {
                    "Key": "error.html"
                }
            }'

          # Add a bucket policy to allow public read access
          aws s3api put-bucket-policy \
            --bucket bw-hunterdle-cs293-project.com \
            --policy '{
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": "*",
                        "Action": "s3:GetObject",
                        "Resource": "arn:aws:s3:::bw-hunterdle-cs293-project.com/*"
                    }
                ]
            }'

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync ./public/ s3://bw-hunterdle-cs293-project.com --delete
